In [41]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline
import seaborn as sns

In [42]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_squared_log_error

**Import** **Dataset**

In [43]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv')

In [44]:
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [45]:
df.head(3)

date  Appliances  lights  ...  Tdewpoint        rv1        rv2
0  2016-01-11 17:00:00          60      30  ...        5.3  13.275433  13.275433
1  2016-01-11 17:10:00          60      30  ...        5.2  18.606195  18.606195
2  2016-01-11 17:20:00          50      30  ...        5.1  28.642668  28.642668

[3 rows x 29 columns]

In [46]:
df.tail(3)

date  Appliances  lights  ...  Tdewpoint        rv1        rv2
19732  2016-05-27 17:40:00         270      10  ...  13.266667  29.199117  29.199117
19733  2016-05-27 17:50:00         420      10  ...  13.233333   6.322784   6.322784
19734  2016-05-27 18:00:00         430      10  ...  13.200000  34.118851  34.118851

[3 rows x 29 columns]

In [47]:
df.describe()

Appliances        lights  ...           rv1           rv2
count  19735.000000  19735.000000  ...  19735.000000  19735.000000
mean      97.694958      3.801875  ...     24.988033     24.988033
std      102.524891      7.935988  ...     14.496634     14.496634
min       10.000000      0.000000  ...      0.005322      0.005322
25%       50.000000      0.000000  ...     12.497889     12.497889
50%       60.000000      0.000000  ...     24.897653     24.897653
75%      100.000000      0.000000  ...     37.583769     37.583769
max     1080.000000     70.000000  ...     49.996530     49.996530

[8 rows x 28 columns]

In [48]:
df.shape

(19735, 29)

**Checking** **for** **null** **values**

In [49]:
df.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [50]:
df.nunique()

date           19735
Appliances        92
lights             8
T1               722
RH_1            2547
T2              1650
RH_2            3376
T3              1426
RH_3            2618
T4              1390
RH_4            2987
T5              2263
RH_5            7571
T6              4446
RH_6            9709
T7              1955
RH_7            5891
T8              2228
RH_8            6649
T9               924
RH_9            3388
T_out           1730
Press_mm_hg     2189
RH_out           566
Windspeed        189
Visibility       413
Tdewpoint       1409
rv1            19735
rv2            19735
dtype: int64

In [51]:
df.lights.unique()

array([30, 40, 50, 70, 60, 10, 20,  0])

**QUESTION 12 - FITTING LINEAR MODEL BETWEEN T2 AND T6**

In [52]:
x = df[['T2']]
y = df['T6']

# creating linear regression
xy_lin_reg = LinearRegression()

# split data
xx_train, xx_test, yy_train, yy_test = train_test_split(x,y, test_size=0.3, random_state=42)

xy_lin_reg.fit(xx_train, yy_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [53]:
# predict
predictxy = xy_lin_reg.predict(xx_test)
predictxy

array([ 2.15578912, 10.01116055,  1.87391554, ...,  4.24758774,
        8.69822311,  4.9893603 ])

In [54]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [55]:
xy_r2 = r2_score(yy_test,predictxy)
round(xy_r2,2)

0.64

**QUESTION 13 AND OTHERS**

In [56]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dff=df.drop(columns=['date','lights'])


normalise_df=pd.DataFrame(scaler.fit_transform(dff), columns=dff.columns)

#feature data for the model
feat_df=normalise_df.drop(columns=['Appliances'])

#target data for the model
target_df=normalise_df['Appliances']


Create Linear Regression object

In [57]:
reg = LinearRegression()

#split data into training and testing data
x_train, x_test,y_train,y_test=train_test_split(feat_df,target_df, test_size=0.3, random_state=42)

#fit the data
reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

**Getting Results**

In [58]:
#get coefficient
coeff = reg.coef_

#get the intercept
inter=reg.intercept_

In [59]:
coeff[:5]

array([-0.00328105,  0.5535466 , -0.23617792, -0.45669795,  0.29062714])

In [60]:
round(inter,3)

0.153

**Making predictions**

In [61]:
pred_y = reg.predict(x_test)
pred_y[:5]

array([0.03322207, 0.24411599, 0.03400024, 0.10537699, 0.02336017])

**MEASURING** **REGRESSION** **PERFORMANCE**

In [62]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

**MAE**

In [66]:
mae = mean_absolute_error(pred_y,y_test)
round(mae,2)

0.05

**RSS - Resdiual Summ of Squares**

In [64]:
rss = np.sum(np.square(y_test - pred_y))
rss.round(2)

45.35

In [74]:
# OR, to confirm
ssr = np.sum((pred_y-y_test)**2)
ssr.round(2)

45.35

**MSE Mean Squared Error**

In [68]:
mse = mean_squared_error(pred_y, y_test)
round(mse,3)

0.008

In [70]:
#other method to confirm
round(np.mean((pred_y-y_test)**2),3)

0.008

**RMSE**-**Root** **Mean** **Squared** **Error**

In [71]:
rmse=np.sqrt(mse)
round(rmse,3)

0.088

In [73]:
r2 = r2_score(y_test, pred_y)
round(r2,2)

0.15

**QUESTION 18 AND OTHERS Training Ridge**

In [76]:
# import ridge
from sklearn.linear_model import Ridge
ridge_regr = Ridge(alpha=0.4)
ridge_regr.fit(x_train, y_train)

Ridge(alpha=0.4, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [79]:
#comparing the effects of regularisation
def get_weights_df(model, features, col_name):
  #this function returns the weight of every feature
  weights = pd.Series(model.coef_, features.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

linear_model_weights = get_weights_df(reg, x_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_regr, x_train, 'Ridge_Weight')

final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')

In [88]:
ridge_pred = ridge_regr.predict(x_test)
ridge_pred[:5]

array([0.03321872, 0.24043824, 0.03461337, 0.10707126, 0.02394352])

In [92]:
ridge_mse = mean_squared_error(ridge_pred, y_test)
ridge_rmse = np.sqrt(ridge_mse)
ridge_rmse.round(3)

0.088

**Training Lasso**

In [93]:
from sklearn.linear_model import Lasso
lasso_regr = Lasso(alpha=0.001)
lasso_regr.fit(x_train, y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [95]:
lasso_weights_df = get_weights_df(lasso_regr, x_train, 'Lasso_Weight')

final_weights = pd.merge(linear_model_weights, lasso_weights_df, on='Features')
lasso_weights_df

Features  Lasso_Weight
0        RH_out     -0.049557
1          RH_8     -0.000110
2            T1      0.000000
3     Tdewpoint      0.000000
4    Visibility      0.000000
5   Press_mm_hg     -0.000000
6         T_out      0.000000
7          RH_9     -0.000000
8            T9     -0.000000
9            T8      0.000000
10         RH_7     -0.000000
11          rv1     -0.000000
12           T7     -0.000000
13           T6      0.000000
14         RH_5      0.000000
15           T5     -0.000000
16         RH_4      0.000000
17           T4     -0.000000
18         RH_3      0.000000
19           T3      0.000000
20         RH_2     -0.000000
21           T2      0.000000
22         RH_6     -0.000000
23          rv2     -0.000000
24    Windspeed      0.002912
25         RH_1      0.017880

In [96]:
lasso_pred = lasso_regr.predict(x_test)

lasso_mse = mean_squared_error(lasso_pred, y_test)
lasso_rmse = np.sqrt(lasso_mse)
lasso_rmse.round(3)

0.094

In [102]:
linear_model_weights.sort_values(by='Linear_Model_Weight')

Features  Linear_Model_Weight
0          RH_2            -0.456698
1         T_out            -0.321860
2            T2            -0.236178
3            T9            -0.189941
4          RH_8            -0.157595
5        RH_out            -0.077671
6          RH_7            -0.044614
7          RH_9            -0.039800
8            T5            -0.015657
9            T1            -0.003281
10          rv1             0.000770
11          rv2             0.000770
12  Press_mm_hg             0.006839
13           T7             0.010319
14   Visibility             0.012307
15         RH_5             0.016006
16         RH_4             0.026386
17           T4             0.028981
18    Windspeed             0.029183
19         RH_6             0.038049
20         RH_3             0.096048
21           T8             0.101995
22    Tdewpoint             0.117758
23           T6             0.236425
24           T3             0.290627
25         RH_1             0.553547

  QUESTION 17